package ru.vext.engine.vulkan.buffer;

import static org.lwjgl.vulkan.VK10.*;

public class BufferType {

    public static final int USAGE_VERTEX = VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
    public static final int USAGE_VERTEX_TRANSFER_SRC = VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
    public static final int USAGE_VERTEX_TRANSFER_DSC = VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_VERTEX_BUFFER_BIT;
    public static final int USAGE_INDEX = VK_BUFFER_USAGE_INDEX_BUFFER_BIT;
    public static final int USAGE_INDEX_TRANSFER_SRC = VK_BUFFER_USAGE_TRANSFER_SRC_BIT | VK_BUFFER_USAGE_INDEX_BUFFER_BIT;
    public static final int USAGE_INDEX_TRANSFER_DSC = VK_BUFFER_USAGE_TRANSFER_DST_BIT | VK_BUFFER_USAGE_INDEX_BUFFER_BIT;

    public static final int MEMORY_TYPE_CPU_VISIBLE = VK_MEMORY_PROPERTY_HOST_VISIBLE_BIT | VK_MEMORY_PROPERTY_HOST_COHERENT_BIT;
    public static final int MEMORY_TYPE_GPU_LOCAL = VK_MEMORY_PROPERTY_DEVICE_LOCAL_BIT;
}
